project:
  type: website

website:
  title: "Evripidis Bantis"
  site-url: https://evripidis-bantis.github.io/
  navbar:
    left:
      - text: "Blog & Projects"
        href: blog.qmd
  search: false

format:
  html:
    theme: [cosmo]
    css: styles.css?v=2